language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: yarn install && yarn run build
  skip_cleanup: true
  on:
    branch: master